### ISSUE TITLE
Failed to load the atom-discord package

### ISSUE THREAD

**Issue by JuanM04** [HelloWorld017/atom-discord#29]
[Enter steps to reproduce:]

1. Download atom-discord form GitHub Repository -> releases
2. Add it to C:\Users\[user]\.atom\packages

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Windows 10 (later than Fall Creator Update)
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 1.4.0

### Stack Trace

Failed to load the atom-discord package

```
At Cannot find module 'bluebird'

Error: Cannot find module 'bluebird'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-discord/src/index.js:4:24)
    at /packages/atom-discord/src/index.js:276:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:903:35)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:617:16)
    at config.transact (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:528:23)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/atom-environment.js:821:34
```

### Commands

```
     -0:14.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.use-animations)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-discord 1.4.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
emmet 2.4.3 
figlet 0.5.4 
file-icons 2.1.14 
highlight-selected 0.13.1 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
seti-syntax 1.1.2 
teletype 0.2.3 
```

**Comment by HelloWorld017** [comment]
You should run `$ npm install` at the package directory!

**Comment by DuckyQuack** [comment]
What is the package directory? Sorry for the stupid question...

**Comment by JuanM04** [comment]
> I ran `npm install` in the package directory after upgrading to 2.0, but I still get the error: `Cannot find module '../i18n/undefined.json'`.

Me too

**Comment by Aimarekin** [comment]
2.0 is currently unstable, @JuanM04 . Try an older version.

**Comment by jasikpark** [comment]
atom auto-updated me to version 2.0 - why is it in the extension library if it isn't stable?

**Comment by Techman** [comment]
@Aimarekin How do you roll back the package?
